#!/usr/bin/env bash

# add entry to lock file - now includes libs
lock_add() {
    GLOBAL="$1"
    REPO="$2"
    PROVIDER="$3"
    BRANCH="$4"
    COMMIT="$5"
    DATE="$6"
    LIBS="$7"
    LOCK=$(get_lock_path "$GLOBAL")
    DIRNAME=$(repo_to_dirname "$REPO")

    grep -q "^\[$REPO\]" "$LOCK" 2>/dev/null && return 0

    mkdir -p "$(dirname "$LOCK")"

    printf "[%s]\ndirname=%s\nprovider=%s\nbranch=%s\ncommit=%s\ndate=%s\nlibs=%s\n\n" \
        "$REPO" "$DIRNAME" "$PROVIDER" "$BRANCH" "$COMMIT" "$DATE" "$LIBS" >> "$LOCK"
}

# read libs field for a repo
lock_get_libs() {
    GLOBAL="$1"
    REPO="$2"
    LOCK=$(get_lock_path "$GLOBAL")

    [ -f "$LOCK" ] || return 1

    awk -v repo="[$REPO]" '
        $0 == repo { found=1; next }
        found && /^\[/ { found=0 }
        found && /^libs=/ { sub(/^libs=/, ""); print; exit }
    ' "$LOCK"
}
# remove entry from lock file
lock_remove() {
    GLOBAL="$1"
    REPO="$2"
    LOCK=$(get_lock_path "$GLOBAL")

    if [ ! -f "$LOCK" ]; then
        echo "[!] Lock file not found"
        return 1
    fi

    # use awk to remove block belonging to repo
    awk -v repo="[$REPO]" '
        /^\[/ { block=$0; found=0 }
        $0 == repo { found=1; block="" }
        !found { print }
        found && /^$/ { found=0 }
    ' "$LOCK" > "$LOCK.tmp" && mv "$LOCK.tmp" "$LOCK"
}

# read single field for a repo from lock file
lock_get_field() {
    LOCK="$1"
    REPO="$2"
    FIELD="$3"

    awk -v repo="[$REPO]" -v field="$FIELD" '
        $0 == repo { found=1; next }
        found && /^\[/ { found=0 }
        found && index($0, field "=") == 1 {
            sub(field "=", ""); print; found=0
        }
    ' "$LOCK"
}

# update commit/version for a repo
lock_ch_version() {
    GLOBAL="$1"
    REPO="$2"
    VERSION="$3"
    LOCK=$(get_lock_path "$GLOBAL")

    if [ ! -f "$LOCK" ]; then
        echo "[!] $REPO not found in lock file"
        return 1
    fi

    sed -i "s/^commit=.*/commit=$VERSION/" "$LOCK"
    echo "[✓] Updated $REPO to $VERSION"
}

# regenerate arsenal.h by scanning vendor dirs
headergen() {
    GLOBAL="$1"
    HEADER=$(get_header_path "$GLOBAL")

    if [ "$GLOBAL" = "1" ]; then
        VENDOR="$ARSENAL_VENDOR"
        GUARD="ARSENAL_H"
    else
        VENDOR="$LOCAL_VENDOR"
        GUARD="ARSENAL_LOCAL_H"
    fi

    mkdir -p "$(dirname "$HEADER")"

    # write header guard
    printf "#ifndef %s\n#define %s\n\n" "$GUARD" "$GUARD" > "$HEADER"
    printf "// auto generated by arsenal - do not edit\n\n" >> "$HEADER"

    # scan each vendor/user@repo dir recursively for .h files
    if [ -d "$VENDOR" ]; then
        for repo_dir in "$VENDOR"/*/; do
            [ -d "$repo_dir" ] || continue
            DIRNAME=$(basename "$repo_dir")
            printf "// %s\n" "$DIRNAME" >> "$HEADER"

            # find all .h files recursively, use absolute path
            find "$repo_dir" -name "*.h" | while read -r hfile; do
                # get real absolute path
                ABSPATH=$(cd "$(dirname "$hfile")" && pwd)/$(basename "$hfile")
                printf "#include \"%s\"\n" "$ABSPATH" >> "$HEADER"
            done

            printf "\n" >> "$HEADER"
        done
    fi

    printf "#endif\n" >> "$HEADER"

    # for global installs also copy header to current project dir
    if [ "$GLOBAL" = "1" ]; then
        LOCAL_COPY="$PWD/arsenal.h"
        if [ -f "$LOCAL_COPY" ]; then
            # replace existing
            cp "$HEADER" "$LOCAL_COPY"
            echo "[✓] Updated arsenal.h in current directory"
        else
            cp "$HEADER" "$LOCAL_COPY"
            echo "[✓] Copied arsenal.h to current directory"
        fi
    fi

    echo "[✓] Generated $HEADER"
}
